account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
app_name = 'account'

urlpatterns = [
  
 
  path('', views.dashboard , name='dashboard'),
  path('alert/create/', views.create_alert,name='create_alert'),
  path('alert/list/',views.alert_list,name='alert_list'),
  path('register/form/',views.register,name='RegisterForm'),
  path('login/',views.LoginView.as_view(),name='login'),
  path('logout',views.LogoutView.as_view(),name='logout'),
  path('academic/calender/',views.academic_calender,name='academic_calender'),
  path('timetable/',views.time_table,name='time_table'),
  path('syllabus/upload/', views.syllabus, name='syllabus'),

  # path('login/',auth_views.LoginView.as_view() , name='login'),
  # path('logout/',auth_views.LogoutView.as_view() , name='logged_out'),
  # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
  # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
  # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
  # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
  # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
  # path('register/',views.register, name='register'),
  # path('account/profile_edit/',views.basic_info ,name = 'edit_profile'),
  # path('account/media_upload/',views.edit_media , name = 'edit_media'),

  # path('account/signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
  # path('account/signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
  # path('account/signup/principal/', views.PrincipalSignUpView.as_view(), name='principal_signup'),
  #

  #All Student url
  path('feeds/', views.feeds, name='feeds'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from django.conf.urls.static import static
from django.conf import settings

from schoolclasses import urls
app_name = 'student'

urlpatterns = [
  path('',views.index,name='dashboard'),
  path('add', views.user_student, name='create_student'),
  path('create/profile/',views.student_profile,name='student_profile'),
  path('login',views.LoginView.as_view(),{'template_name': 'student/login.html'},name='login'),
  path('logout', views.LogoutView.as_view(),  name='logout'),
  path('view/<int:id>/',views.student_details_view,name='student_detail'),
  path('list/', views.student_list_view, name='student_list'),
  path('basic/',views.student_basic_info , name='basic_student'),
  path('feeds/', views.feed, name='feeds'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vidyarthi/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home,name='home' ),
    path('account/', include('account.urls', namespace='account')),
    path('student/',include('student.urls', namespace='student')),
    path('schoolclasses', include('schoolclasses.urls',namespace='school')),
    path('employes/', include('employes.urls',namespace='employes')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from account.models import User
from schoolclasses.models import *


class StudentProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='student_user',null=True,blank=True)
    student_name = models.CharField(max_length=20)
    student_class = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='student_class')
    student_section = models.ForeignKey(Section, null=True,blank=True, on_delete=models.CASCADE, related_name='student_section')
    student_roll_number = models.PositiveIntegerField()
    student_reg_number = models.CharField(max_length=20)
    student_previous_school = models.CharField(max_length=20)
    student_previous_school_transfer_certificate = models.ImageField(null=True,blank=True)
    father_name = models.CharField(max_length=20)
    mother_name = models.CharField(max_length=20)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
    message="Phone number must be entered in the format: '8885559997'. Up to 12 digits allowed along with country code.")
    guardian_mobile_number = models.CharField(validators=[phone_regex], max_length=12)
    parents_email_id = models.EmailField()
    student_email_id = models.EmailField()
    family_photo = models.ImageField(null=True, blank=True)
    date_of_birth = models.DateField()
    home_address = models.CharField(max_length=60, null=True, blank=True)

    def __str__(self):
        return self.student_name

student/forms.py
from django.forms.widgets import DateInput
from django import forms
from .models import StudentProfile
from django.contrib.auth.forms import AuthenticationForm


class StudentProfileForm(forms.ModelForm):
  class Meta:
    model = StudentProfile
    fields = '__all__'
    exclude=('user',)
    widgets = {
    'date_of_birth': DateInput(attrs={'type': 'date'}),
     }



class LoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
      if not user.is_student:
        raise forms.ValidationError('This is only for Student login page', code='inactive')

student/views.py
from django.shortcuts import render,redirect
from account.models import *
from django.contrib.auth.decorators import login_required
from account.decorators import student_required
from django.contrib.auth.views import LoginView,LogoutView
from student.forms import *
from.models import *
from account.forms import RegisterForm
# Create your views here.
@login_required
def student_basic_info(request):
    if request.method == 'POST':
        basic_student = StudentProfileForm(instance= request.user.studentprofile,
                                            data = request.POST)
        if basic_student.is_valid():
            basic_student = basic_student.save(commit=False)
            basic_student.save()
    else:
        basic_student = StudentProfileForm(instance= request.user.studentprofile)
    return render(request,'profile.html',{'basic_student':basic_student})

def index(request):
    return render(request,'student/adminlte/index.html',{})


class Login(LoginView):
    authentication_form = LoginForm
    template_name = 'student/login.html'
    success_url = 'student:dashboard'

class Logout(LogoutView):
    success_url = '/'


@login_required
@student_required
def feed(request):
    alert = Alert.objects.all()
    return render(request, 'student/dashbord/student_feed.html',{'alert':alert})


def user_student(request):
    if request.method == 'POST':
        student_form=RegisterForm(request.POST)
        if student_form.is_valid():
            new_user =student_form.save(commit=False)
            new_user.set_password('password')
            new_user.is_student=True
            new_user.save()
            return redirect('student:student_profile')
    else:
        student_form =RegisterForm()
    return render(request,'student/create_student.html',{'student_form':student_form})


def student_profile(request):
    if request.method == 'POST':
        profile_form = StudentProfileForm(request.POST)
        if profile_form.is_valid():
            profile_form.save(commit=False)
            user = User.objects.all().last()
            userid = user.id
            profile_form.user = userid
            profile_form.save()
        return redirect('account:create_alert')
    else:
        profile_form = StudentProfileForm(request.POST)
    return render(request, 'student/student_profile_add.html', {'pro_user': profile_form})



def student_list_view(request):
    student_list = StudentProfile.objects.all()
    return render(request,'student/dashbord/student_list.html',{'std_info':student_list})

def student_details_view(request, id):
    std_detail = StudentProfile.objects.get(id=id)
    return render(request,'student/student_profile.html',{'std_detail':std_detail})

templates/student/dashbord/student_detail.html
{% extends 'account/adminlte/account_base.html' %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{# Display a form #}


{% block content %}
               <div class="container theme-showcase margin-top-navbar" role="main">
                    <a class="btn btn-outline-secondary float-right" href="{% url 'account:student:create_student' %}" role="button"> Add Student</a>
        <div class="col-md-12">
            {% for foo in std_detail %}
                <h1>{{ foo.student_name }}</h1>
            {% endfor %}

        </div>
      </div>
{% endblock %}

templates/student/dashbord/student_feed.html
{% extends 'student/adminlte/base.html' %}

{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{# Display a form #}


{% block content %}

    <div class="container-fluid gedf-wrapper">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <div class="h5">Student profile</div>
                        <div class="h7 text-muted">Fullname : student name here</div>
                        <div class="h7">Descriptions here
                        </div>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="h6 text-muted">Followers</div>
                            <div class="h5">5.2342</div>
                        </li>
                        <li class="list-group-item">
                            <div class="h6 text-muted">Following</div>
                            <div class="h5">6758</div>
                        </li>
                        <li class="list-group-item">Vestibulum at eros</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6 gedf-main">

                <!--- \\\\\\\Post-->


{#                <div class="card gedf-card">#}
{#                    <div class="card-header">#}
{#                        <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">#}
{#                            <li class="nav-item">#}
{#                                <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make#}
{#                                    a publication</a>#}
{#                            </li>#}
{#                            <li class="nav-item">#}
{#                                <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>#}
{#                            </li>#}
{#                        </ul>#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                        <div class="tab-content" id="myTabContent">#}
{#                            <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">#}
{#                                <div class="form-group">#}
{#                                    <label class="sr-only" for="message">post</label>#}
{#                                    <textarea class="form-control" id="message" rows="3" placeholder="What are you thinking?"></textarea>#}
{#                                </div>#}
{##}
{#                            </div>#}
{#                            <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">#}
{#                                <div class="form-group">#}
{#                                    <div class="custom-file">#}
{#                                        <input type="file" class="custom-file-input" id="customFile">#}
{#                                        <label class="custom-file-label" for="customFile">Upload image</label>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <div class="py-4"></div>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="btn-toolbar justify-content-between">#}
{#                            <div class="btn-group">#}
{#                                <button type="submit" class="btn btn-primary">share</button>#}
{#                            </div>#}
{#                            <div class="btn-group">#}
{#                                <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"#}
{#                                    aria-expanded="false">#}
{#                                    <i class="fa fa-globe"></i>#}
{#                                </button>#}
{#                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">#}
{#                                    <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public</a>#}
{#                                    <a class="dropdown-item" href="#"><i class="fa fa-users"></i> Friends</a>#}
{#                                    <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Just me</a>#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}

                <!-- Post /////-->

                <!--- \\\\\\\Post-->
                {% for foo in alert %}


                <div class="card gedf-card">
                    <div class="card-header">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">
                                    <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                                </div>
                                <div class="ml-2">
                                        <div class="h5 m-0">student mane</div>

                                    <div class="h7 text-muted">roll number of the student or if teacher then show subject </div>
                                </div>
                            </div>
                            <div>
                                <div class="dropdown">
                                    <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-h"></i>
                                    </button>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                        <div class="h6 dropdown-header">Configuration</div>
                                        <a class="dropdown-item" href="#">Save</a>
                                        <a class="dropdown-item" href="#">Hide</a>
                                        <a class="dropdown-item" href="#">Report</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <div class="card-body">
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>10 min ago</div>
                        <a class="card-link" href="#">

                            <h5 class="card-title">{{ foo.title }}</h5>
                        </a>
                        <p class="card-text">
                            {{ foo.message }}
                        </p>
                         {% if foo.image %}
                             <img src="{{ foo.image.url }}" height="400" width="400">
                         {% endif %}
                    {% if foo.video %}
                        <video   width="500" height="400" controls>
                          <source src="{{ foo.video.url }}" type="video/mp4">
                        </video>
                    {% endif %}
                    </div>
                    <div class="card-footer">
                        <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                        <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                        <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
                    </div>
                </div>
                {% endfor %}

                <!-- Post /////-->




                <!--- \\\\\\\Post-->
                <!-- Post /////-->



            </div>
            <div class="col-md-3">
                <div class="card gedf-card">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                            card's content.</p>
                        <a href="#" class="card-link">Card link</a>
                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
                <div class="card gedf-card">
                        <div class="card-body">
                            <h5 class="card-title">Card title</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                                card's content.</p>
                            <a href="#" class="card-link">Card link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/student/dashbord/student_list.html
{% extends 'account/adminlte/account_base.html' %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{# Display a form #}


{% block content %}
               <div class="container theme-showcase margin-top-navbar" role="main">
                    <a class="btn btn-outline-secondary float-right" href="{% url 'student:create_student' %}" role="button"> Add Student</a>
              <table class="table table-striped">
                <thead>
                  <tr>
                      <th>Students</th>
                  </tr>
                </thead>
                <tbody>
                  {% for emp in std_info %}
                    <tr>
                      <td><a href="{% url 'student:student_detail' emp.id %}">{{ emp.student_name }}</a></td>
                        <td class="float-right"><a href=".">Delete</a></td>
                        <td class="float-right" style="margin-right: 0.5px;"><a href=".">Edit</a></td>
                    </tr>
                 {% endfor %}
                </tbody>
              </table>
           </form>
        </div>
      </div>
{% endblock %}