account/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
app_name = 'account'

urlpatterns = [
  
 
  path('', views.dashboard , name='dashboard'),
  path('alert/create/', views.create_alert,name='create_alert'),
  path('alert/list/',views.alert_list,name='alert_list'),
  path('register/form/',views.register,name='RegisterForm'),
  path('login/',views.LoginView.as_view(),name='login'),
  path('logout',views.LogoutView.as_view(),name='logout'),
  path('academic/calender/',views.academic_calender,name='academic_calender'),
  path('timetable/',views.time_table,name='time_table'),
  path('syllabus/upload/', views.syllabus, name='syllabus'),

  # path('login/',auth_views.LoginView.as_view() , name='login'),
  # path('logout/',auth_views.LogoutView.as_view() , name='logged_out'),
  # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
  # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
  # path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
  # path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
  # path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
  # path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
  # path('register/',views.register, name='register'),
  # path('account/profile_edit/',views.basic_info ,name = 'edit_profile'),
  # path('account/media_upload/',views.edit_media , name = 'edit_media'),

  # path('account/signup/student/', views.StudentSignUpView.as_view(), name='student_signup'),
  # path('account/signup/teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
  # path('account/signup/principal/', views.PrincipalSignUpView.as_view(), name='principal_signup'),
  #

  #All Student url
  path('feeds/', views.feeds, name='feeds'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employes/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import auth_login
from .import views
from .forms import LoginForm

app_name = 'employes'


urlpatterns = [
  path('teacher/',views.dashbord,name='dashbord'),
  path('teacher/feeds/',views.feeds,name='employes_feeds'),
  path('teacher/alert/',views.create_alert,name='create_alert'),
  path('teacher/alert/list/',views.alert_list,name='alert_list'),
  path('teacher/add',views.teacher, name='teacher_add'),
  path('teacher/add/profile',views.Teacher_Profile,name='teacher_profile_add'),
  path('teacher/profile/<int:id>/',views.teacher_profile_detail,name='teacher_profile_detail'),
  path('teacher/list', views.teacher_list_view, name='teacher_list'),
  path('homework/list', views.homework_list_view, name='homework_list'),
  path('assignment/list', views.assignment_list_view, name='assignment_list'),
  # path('homework/delete/<int:id>', views.homework_delete, name = 'confirm_delete_homework'),
  path('teacher/login/',views.LoginView.as_view(),name='login'),
  path('teacher/logout',views.LogoutView.as_view(),name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

schoolclasses/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views

app_name = 'schoolclass'

urlpatterns = [
  path('class/view',views.view_class, name='class_list'),
  path('class/add',views.add_class, name='clas_add'),
  path('section/add',views.add_section,name='section_add'),
  path('section/view', views.list_section, name='section_view'),
]

student/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
from django.conf.urls.static import static
from django.conf import settings

from schoolclasses import urls
app_name = 'student'

urlpatterns = [
  path('',views.index,name='dashboard'),
  path('add', views.user_student, name='create_student'),
  path('create/profile/',views.student_profile,name='student_profile'),
  path('login',views.LoginView.as_view(),{'template_name': 'student/login.html'},name='login'),
  path('logout', views.LogoutView.as_view(),  name='logout'),
  path('view/<int:id>/',views.student_details_view,name='student_detail'),
  path('list/', views.student_list_view, name='student_list'),
  path('basic/',views.student_basic_info , name='basic_student'),
  path('feeds/', views.feed, name='feeds'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vidyarthi/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.home,name='home' ),
    path('account/', include('account.urls', namespace='account')),
    path('student/',include('student.urls', namespace='student')),
    path('schoolclasses', include('schoolclasses.urls',namespace='school')),
    path('employes/', include('employes.urls',namespace='employes')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/employes/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong> All rights
    reserved.
    {% endblock %}
    {% endblock %}
</footer>

templates/employes/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>F</b>A{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Fella</b>Admin{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

templates/employes/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}MAIN NAVIGATION{% endblock %}</li>

            {% block nav_links %}
                <li>
                    <a href="{% url 'employes:dashbord' %}">
                        <i class="fa fa-dashboard"></i> <span>Dashbord</span>
                    </a>
                </li>
                    <li>
                    <a href="{% url 'employes:employes_feeds' %}">
                        <i class="fa fa-feed"></i> <span>Feeds</span>
                    </a>
                </li>

{#                Teacher add Block for teacher Dashbord#}



{#                <li class="treeview">#}
{#                    <a href="#">#}
{#                        <i class="fa fa-group"></i> <span>Teachers</span>#}
{#                        <span class="pull-right-container">#}
{#                            <i class="fa fa-angle-left pull-right"></i>#}
{#                        </span>#}
{#                    </a>#}
{#                    <ul class="treeview-menu">#}
{#                        <li>#}
{#                            <a href="{% url 'employes:teacher_add' %}">#}
{#                                <i class="fa fa-plus"></i> Add Teacher#}
{#                            </a>#}
{#                        </li>#}
{#                        <li>#}
{#                            <a href="{% url 'employes:teacher_list' %}">#}
{#                                <i class="fa fa-list"></i> View Teachers#}
{#                            </a>#}
{#                        </li>#}
{#                    </ul>#}
{#                </li>#}
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-graduation-cap"></i> <span>Students</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
{#                        <li>#}
{#                            <a href="{% url 'student:create_student' %}">#}
{#                                <i class="fa fa-plus"></i> Add Student#}
{#                            </a>#}
{#                        </li>#}
                         <li>
                            <a href="{% url 'student:student_list' %}">
                                <i class="fa fa-list"></i> View Students
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-list"></i> Student Day Attendance
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-group"></i> <span>Alerts</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'employes:create_alert' %}">
                                <i class="fa fa-plus"></i> Add Alert
                            </a>
                        </li>
                         <li>
                            <a href="{% url 'employes:alert_list' %}">
                                <i class="fa fa-list"></i> View Alert
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-cc-mastercard"></i> <span>Admin</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
{#                        <li>#}
{#                            <a href="{% url 'schoolclass:clas_add' %}">#}
{#                                <i class="fa fa-plus"></i> Add Class#}
{#                            </a>#}
{#                        </li>#}

{#                         <li>#}
{#                            <a href="{% url 'schoolclass:section_add' %}">#}
{#                                <i class="fa fa-plus"></i> Add Section#}
{#                            </a>#}
{#                        </li>#}
                         <li>
                            <a href="{% url 'schoolclass:class_list' %}">
                                <i class="fa fa-list"></i> View Class
                            </a>
                        </li>
                         <li>
                            <a href="{% url 'schoolclass:section_view' %}">
                                <i class="fa fa-list"></i> Add Section
                            </a>
                        </li>
                    </ul>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

templates/employes/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/employes/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

templates/employes/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "jquery/dist/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %} "></script>
<script src="{% static "admin-lte/dist/js/app.min.js" %}"></script>
{% endblock %}

templates/employes/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/AdminLTE.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/skins/_all-skins.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "icheck/skins/square/blue.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "conflicts/conflicts.css" %}">
{% endblock %}